a = input('Digite algo:')
print('O tipo primitivo desse valor é', type(a))
print('Só tem espaços? ', a.isspace())
print('É um número?', a.isnumeric())
print('É uma alfabético ?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('Está em maiúsculas?', a.isupper())
print('Está em minúsculas?', a.islower())
print('está capitalizada? ', a.istitle())


print(a.isascii())
print(a.isdigit())
print(a.isdecimal())
print(a.isidentifier())
print(a.isprintable())
